name = "helios"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Justin Wyffels"]
maintainers = ["Justin Wyffels <justinwyffels@gmail.com>"]
maintainers-logins = ["jwyffels2"]

executables = ["helios"]

[[depends-on]]
gnat_riscv64_elf = "14.2.1"
bare_runtime = "14.0.0"
neorv32_hal = "*"

[[pins]]
neorv32_hal = {path = "third_party/helios-neorv32-setups/neorv32-hal"}
[gpr-set-externals]
BARE_RUNTIME_SWITCHES = "-march=rv32i_zicsr_zifencei -mabi=ilp32"

