name = "helios"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Justin Wyffels"]
maintainers = ["Justin Wyffels <justinwyffels@gmail.com>"]
maintainers-logins = ["jwyffels2"]

executables = ["helios"]

[[depends-on]]
helios_env = "*"

[[pins]]
helios_env = {path = "./helios_env"}
